Ben sprint 4
kylegessel/sprintfinity3902 pull request #71
Opened 2021-04-04 12:01 UTC by bjhobson12

This pr allows hands to track lnk using bfs. It doesn't seem to have performance issues and is updated at every tile so the hands can constantly follow him. When a hand has caught link, it will animate out in a relatively cool spiral. Then the game should be reset to the main dungeon... and I really mean reset... there are enough variables changed in handenemy it might be safer to reset. We could try just changing the currentroom, but I have not tested that.

2021-04-05 14:53 UTC, kylegessel requested changes
Brad and I both had I instant reaction to seeing how the new hand enemies. Watching the hands path to link was great and then the animation after you get caught was just the cherry on top. This is so damn cool.

I made alot of comments reading through this code.

I know this code presently breaks the HUD, which is a major concern. I see that you are making methods that link can call to update the commands, but those don't seem implemented as of now. 

The reason we held off on commands like that is that we decided HUD should see link information but maybe we could avoid Link needing to know anything about HUD. By the nature of the HUD it HAS to know about link anyway (to check his health etc) so creating booleans for the HUD to check felt like an ok solution. I think we should have a discussion about this.

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/Dungeon/RoomLoader.cs
>          }
This looks like a big change to the RoomLoader that I'm not quite sure I understand.

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/Dungeon/RoomLoader.cs
>          }
I get the the hand needs to know link's location, but does the Initialize still occur?

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/Entities/Enemies_NPCs/HandEnemy.cs
> +        private static float F_DOT_THREE = .4f;
Name doesn't match reality anymore. I think we should change our Magic number variables to descriptive names (in this case, something like ENTITY_SPEED) so we don't have to update both the number and the variable name.

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/Entities/Link/DamagedLink.cs
> +                decoratedLink.Sprite = value;
What do these changes give us?

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/Interfaces/IEntity.cs
> +        }
If this isn't a constant, I don't think it should be capitalized.

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/States/ItemPickup/BlueRupeePickup.cs
> -            Link.itemPickedUp = true;
This removal in item classes broke the HUD

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/States/ItemPickup/BlueRupeePickup.cs
> -            Link.itemPickedUp = true;
As it stands, the boolean is how we tell the HUD something has happened. I don't think its ideal, but it is still required in the current code base.

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/Interfaces/IPlayer.cs
> +        void TogglePlayerVisible();
Is this for the updated lose state?

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/States/ItemPickup/BlueRupeePickup.cs
> -            Link.itemPickedUp = true;
I think UpdateSelf command is supposed to replace this, but it doesn't look complete.

2021-04-05 14:53 UTC, kylegessel commented on Sprintfinity3902/Entities/Enemies_NPCs/BlueBatEnemy.cs
> +            Collidable = false;
Looks like an accident here.

2021-04-09 17:32 UTC, bjhobson12 commented
This pr is out of date... will re-request when ready. Thank you all for the comments.

2021-04-09 17:32 UTC, closed without merging